// import type { Metadata } from "next";
import Footer from "@/components/Footer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AtomLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {children}
      <Footer></Footer>
    </>
      
  );
}
